services:
  db:
    image: postgres:alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - 5432:5432
    volumes:
      - ecommerce_data:/var/lib/postgresql/data

volumes:
  ecommerce_data: