services:
  db:
    image: postgres:alpine
    container_name: ecommerce-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce_db
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
  spring-app:
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  ecommerce_data: