spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ecommerce_db

jwt-public-key: classpath:jwt-public.pem
jwt-private-key: classpath:jwt-private.pem
refresh-token-public-key: classpath:refresh-public.pem
refresh-token-private-key: classpath:refresh-private.pem
